name: Build and deploy Dockerized Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: 66e2c080-70cb-45fa-b8cd-b95bc7104d97
          tenant-id: 298d77e5-a38c-4dfa-9203-24f85a6eabbb
          subscription-id: 1a4fc747-a4d7-4a7d-9276-264dc808ed8b
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: akscontainerregistry22.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t akscontainerregistry22.azurecr.io/portfolio:latest ./frontend
          docker push akscontainerregistry22.azurecr.io/portfolio:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portfolio'  # Change this if your Azure Web App name is different
          slot-name: 'Production'
          images: 'akscontainerregistry22.azurecr.io/portfolio:latest'
