name: Build and deploy Dockerized Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # ✅ REQUIRED for Azure OIDC login
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: fd2f0856-384f-48e7-a13c-5d81da431316
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CACABF78E2664B62976E3819F3877FF5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DDCF9A3E4F14714B758E4859A079050 }}

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: akscontainerregistry22.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t akscontainerregistry22.azurecr.io/portfolio:latest .
          docker push akscontainerregistry22.azurecr.io/portfolio:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portfolio'  # Change this if your Azure Web App name is different
          slot-name: 'Production'
          images: 'akscontainerregistry22.azurecr.io/portfolio:latest'
